name: build
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        uses: vman101/workflow-test/configure-git@main
        id: git-setup
        with:
          client-id: ${{ vars.GLOBAL_APP_EVVA_BEE_APP_ID }}
          private-key: ${{ secrets.GLOBAL_APP_EVVA_BEE_PRIVATE_KEY }}
          github-host: github.com

      - name: Build Package
        id: build-package
        uses: vman101/workflow-test/build-npm@main
