name: cache
on:
  pull_request:
    types:
      - closed
permissions:
  contents: read
jobs:
  cache_cleanup:
    name: Clean up cache
    uses: evva-sfw/workflows/.github/workflows/call_cache.yml@main
